
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.redhat.samples.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-05-12T09:30:53.357+05:30
 * Generated source version: 3.0.4
 *
 */

@javax.jws.WebService(
                      serviceName = "GreetingService",
                      portName = "GreetingServicePort",
                      targetNamespace = "http://ws.samples.redhat.com/",
                      wsdlLocation = "file:/Viral_Data/dev_workspace/cxf-JaxwsCatalog/src/main/resources/META-INF/wsdl/greeting.wsdl",
                      endpointInterface = "com.redhat.samples.ws.GreetingService")

public class GreetingServiceImpl implements GreetingService {

    private static final Logger LOG = Logger.getLogger(GreetingServiceImpl.class.getName());


    public java.lang.String goodbye(java.lang.String name) {
        LOG.info("Executing operation goodbye");
        System.out.println(name);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    public java.lang.String hello(java.lang.String name) {
        LOG.info("Executing operation hello");
        System.out.println(name);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
