
package com.example.customerservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4.redhat-621084
 * 2016-07-26T17:39:28.429+05:30
 * Generated source version: 3.0.4.redhat-621084
 */

@WebFault(name = "NoSuchCustomer", targetNamespace = "http://customerservice.example.com/")
public class NoSuchCustomerException extends Exception {
    
    private com.example.customerservice.NoSuchCustomer noSuchCustomer;

    public NoSuchCustomerException() {
        super();
    }
    
    public NoSuchCustomerException(String message) {
        super(message);
    }
    
    public NoSuchCustomerException(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchCustomerException(String message, com.example.customerservice.NoSuchCustomer noSuchCustomer) {
        super(message);
        this.noSuchCustomer = noSuchCustomer;
    }

    public NoSuchCustomerException(String message, com.example.customerservice.NoSuchCustomer noSuchCustomer, Throwable cause) {
        super(message, cause);
        this.noSuchCustomer = noSuchCustomer;
    }

    public com.example.customerservice.NoSuchCustomer getFaultInfo() {
        return this.noSuchCustomer;
    }
}
