package com.redhat.samples.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2015-06-29T18:04:19.953+05:30
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://ws.samples.redhat.com/", name = "GreetingService")
@XmlSeeAlso({ObjectFactory.class})
public interface GreetingService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "goodbye", targetNamespace = "http://ws.samples.redhat.com/", className = "com.redhat.samples.ws.Goodbye")
    @WebMethod
    @ResponseWrapper(localName = "goodbyeResponse", targetNamespace = "http://ws.samples.redhat.com/", className = "com.redhat.samples.ws.GoodbyeResponse")
    public java.lang.String goodbye(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://ws.samples.redhat.com/", className = "com.redhat.samples.ws.Hello")
    @WebMethod
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://ws.samples.redhat.com/", className = "com.redhat.samples.ws.HelloResponse")
    public java.lang.String hello(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
