package com.redhat.samples.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2015-06-29T18:04:20.002+05:30
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "GreetingService", 
                  wsdlLocation = "file:/Viral_Data/Projects_To_Deploy/Fuse/camelRoutes/cxfSchemaValidation/src/main/resources/wsdl/greeting.wsdl",
                  targetNamespace = "http://ws.samples.redhat.com/") 
public class GreetingService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.samples.redhat.com/", "GreetingService");
    public final static QName GreetingServicePort = new QName("http://ws.samples.redhat.com/", "GreetingServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Viral_Data/Projects_To_Deploy/Fuse/camelRoutes/cxfSchemaValidation/src/main/resources/wsdl/greeting.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GreetingService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Viral_Data/Projects_To_Deploy/Fuse/camelRoutes/cxfSchemaValidation/src/main/resources/wsdl/greeting.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GreetingService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GreetingService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GreetingService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GreetingService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GreetingService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GreetingService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns GreetingService
     */
    @WebEndpoint(name = "GreetingServicePort")
    public GreetingService getGreetingServicePort() {
        return super.getPort(GreetingServicePort, GreetingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GreetingService
     */
    @WebEndpoint(name = "GreetingServicePort")
    public GreetingService getGreetingServicePort(WebServiceFeature... features) {
        return super.getPort(GreetingServicePort, GreetingService.class, features);
    }

}
